### ISSUE TITLE
Add PLX to Travis CI

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#109]
Travis CI does not build acquisition due to  missing PLX libraries.
## Expected Behavior
Adding PLX libraries to Travis CI will allow for compiling of the acquisition, further testing for bugs and compilation issues

## Current Behavior
Travis CI does not build Acquisition due to missing PLX library.

## Context
We want to test acquisition builds.

## Acceptance Criteria

1. TravisCI builds all Acquisition components successfully

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#109
