### ISSUE TITLE
Experiment Processors always plot VANDLE histograms

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#124]
## Expected Behavior

Experiment processors should only plot histograms defined in their DeclarePlots. 
## Current Behavior

Experiment Processors only plot VANDLE histograms and some VANDLE Root Trees. 
## Context

Trying to analyze data using an ExperimentProcessor. This error was mentioned by @jjvz while working on [jjvz/feature-dev](https://github.com/jjvz/paass-laughing-conqueror/tree/feature-dev). 
## Acceptance Criteria

1. Experiment processors plot the appropriate information into the ROOT file. 

### Your Environment

| Component | Value  |
|--|--|
|Operating system | ubuntu |
|Kernel Version   | 4.4.0-43-Microsoft  |
|CMake Version    | 3.5.1 |
|GCC Version      | gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609 |
|ROOT Version     | 6.13/01 |
|GSL Version      | 2.4 |

### Steps to Reproduce

1. Scan a file using dev
2. View histogram names. 

### Screenshots
![image](https://user-images.githubusercontent.com/1553042/36705457-39053fea-1b33-11e8-892c-ffed62fb2e9f.png)
![image](https://user-images.githubusercontent.com/1553042/36705465-43daa324-1b33-11e8-97ad-f0b7a522129c.png)

**Comment by spaulaus** [comment]
From what I can tell of this error, the Experiment Processor defines its own TFile, then this ends up overwriting the TFile defined by the RootHandler.

**Comment by spaulaus** [comment]
I also notice significant differences in the output from Unpacker and ScanInterface. This suggests that there's something deeper going on than what we initially thought.

**Comment by spaulaus** [comment]
I don't seem to have any of the same effects in my ROOT file: 
![image](https://user-images.githubusercontent.com/1553042/36706134-675ff472-1b36-11e8-96d9-9deef085b42a.png)

**Comment by spaulaus** [comment]
As I was drifting to sleep, I realized this might be due to loading shared libraries at run time. 
@jjvz : Try unloading `pixieSuite` from the system, check the library paths, and run the software from the local directory.

**Comment by spaulaus** [comment]
@jjvz : Can you provide some additional details around this error? What is the command you're using to run the analysis software? What is the output of `which utkscan` and `which utkscanor` ?

**Comment by spaulaus** [comment]
This is a bit of a mystery since those histogram numbers are only requested if the `Anl1471Processor` is requested in the configuration file.

**Comment by jjvz** [comment]
I run utkscan and utkscanOR from the respective installation "~/.../install/bin directories.
What I did was to clone the master repo into directory "jj-paass-master" with the ccmake flags as suggested for the pacman polling scenario(video). Form its install/bin directory I run ./utkscanor.
I also created a directory jj-paass-pr270 which is a clone of the dev branch. From its /install/bin/ directory I then run ./utkscan.  
For both cases I have added my Pr248processor and the correction in CMakeList.txt in the source, as well as adding them to the DetectorDriverXmlParser.xml file in the core source.
Never do I include any mention of the Anl1471Processor in any of the files or xml configs.
Also in both cases my custom logfile "<outputfile>.diag", defined and called in the Pr248Processor is not being created and filled.
The output of "which utkscanor" is "not found", and that of "which utkscan" is /opt/paass/bin/utkscan -- the global install (though I'm running ./utkscan from its install/bin folder...

**Comment by spaulaus** [comment]
Found the issue! You're adding the `Anl1471Processor` instead of the `Pr248Processor` or `Pr270Processor` in `DetectorDriverXmlParser::ParseProcessors()`. 
![image](https://user-images.githubusercontent.com/1553042/36898960-079542d8-1deb-11e8-9e9d-6fe628c84bab.png)

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#124
