### ISSUE TITLE
Development Workflow: Adding new files to Git repository -> "git add -A" command

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-laughing-conqueror#125]
In the "Development Workflow" it would be best to add a line reminding the user to "git add -A" before committing changes... I forget and then my repo is incomplete.
## Expected Behavior
Guide reminds user to "git add -A" before committing changes

## Current Behavior
Guide does not have "git add -A" as part of instructions under Step 3 and Step 6.

## Context
I forget to add newly created file, so the repo is incomplete.

## Possible Solution (optional)
Add  "git add -A" as part of instructions under Step 3 and Step 6.

## Acceptance Criteria
1. Consider adding  "git add -A" as part of instructions under Step 3 and Step 6.

**Comment by spaulaus** [comment]
Wiki is updated. I do not recommend using the `-A` flag. That can be dangerous.
