### ISSUE TITLE
git: the "-p" flag in "git rebase -p <branch>" command gives error

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-laughing-conqueror#127]
According to the Development Workflow wiki, we use the "-p" flag in "git rebase -p <branchname>" command, but his gives error 

## Expected Behavior
"git rebase -p <branchname>" command accepted without error

## Current Behavior
"git rebase -p upstream/dev" or "git rebase -p upstream-dev" commands gives this error: 
fatal: Needed a single revision
invalid upstream –p 

## Context
Step 5 - Keep your feature branch updated
git fetch --all --prune
git checkout upstream-dev
**git rebase -p upstream/dev**
git checkout feature-[descriptor]
**git rebase -p upstream-de**v

### Your Environment

| Component | Value  |
|--|--|
|Operating system | <Your OS Here> |
|Kernel Version   | <output of `uname -r`> |
|CMake Version    | <output of `cmake --version`> |
|GCC Version      | <output of `gcc --version`> |
|ROOT Version     | <optional output of `root-config --version`> |
|GSL Version      | <optional output of `gsl-config --version`> |

### Steps to Reproduce
1. Follow step 5 from Development Workflow 
2.
3.

**Comment by spaulaus** [comment]
Make sure you run `git rebase -p upstream/dev` when you have the `upstream-dev` branch checked out. And run `git rebase -p upstream-dev` when you have your feature branch checked out. Use `git status` to determine the checked out branch.

**Comment by spaulaus** [comment]
The command `git rebase -p` command requires that you tell git what branch you want to rebase against. It will always require another argument.

**Comment by spaulaus** [comment]
@jjvz : Any updates on this issue?

**Comment by jjvz** [comment]
You can delete this issue... I think there were underlying problems with the creation of the branches in the first place. Tx.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#127
