### ISSUE TITLE
In SheCorrelator.cpp, refers to header "Exceptions.hpp" - cannot find this file

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-laughing-conqueror#128]
In SheCorrelator.cpp, refers to header "Exceptions.hpp" - cannot find this file
## Current Behavior
When installing the master branch, the compiler gives error - cannot find "Exceptions.hpp" referred to in SheCorrelator.cpp

## Context
make -j8 of the master branch

## Possible Solution (optional)
Change "Exceptions.hpp" to "PaassExceptions.hpp" ??
Some other problems arises: 
SheCorrelator.cpp:67:38: error: ‘GeneralWarning’ was not declared in this scope
         throw GeneralWarning(ss.str()); 
so the solution may be deeper?

## Acceptance Criteria
1. Successful compilation 
2. 
3. 

### Your Environment
| Component | Value  |
|--|--|
|Operating system | <CentOS 7> |
|Kernel Version   | 3.10.0-693.11.6.el7.x86_64 |
|CMake Version    | cmake version 3.9.1 |
|GCC Version      | gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16) |
|ROOT Version     | <optional output of `root-config --version`> |
|GSL Version      | 2.4 |

### Steps to Reproduce
1. git clone https://github.com/jjvz/paass-laughing-conqueror.git 
2. git checkout master
3. make clean && make -j8 install

(the repo above was forked and rebased from upstream master ())

**Comment by jjvz** [comment]
OK, this is not an issue. I found the problem - The CMakeCache.txt file in the source folder should have SheCorrelator.cpp commented out. The original version is correct.

**Comment by spaulaus** [comment]
Take care reusing the same build files after rebasing or swapping branches. It can lead to all kinds of strange compilation / linker errors.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#128
