### ISSUE TITLE
Clean up hribf_buffers.h and rewrite data classes

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#13]
This has way too many classes housed inside of it. These need to be broken out into their components, and abstracted.

**Comment by spaulaus** [comment]
# Current Plan
I am trying to mimic what's in hribf_buffers.h. I want to expand this to do a better abstraction of the base classes. This is leading to a lot of new headers, but some of these are self-contained headers and do not require any source files. This framework allows us to unit-test the different components fairly trivially. 

## Classes 
The top level are abstracted classes. The nested levels are classes that are derived from the abstractions. 
- FileBuffer - An abstracted class adapted from BufferType in hribf_buffers.h
     - PldHeader
     - PldData
     - LdfDir
     - LdfHeader
     - LdfData
     - LdfEndOfFile
- DataFile
     - PldFile
     - LdfFile
     - KissFile

# Alternative Plan
As an alternative. I've considered stuffing all of the buffer definitions into the DataFile class. This would help minimize the number of classes we have defined. 
### Pros
- DataFile (and children) are self-contained with all the information they need. 
- Adding new data formats fairly trivial
- Easier to modify the default behavior of classes since we have a single abstract base. 
- Changes can be propagated automatically to Unpacking
- Smaller codebase

### Cons
- It's could be a little more difficult to figure out what some of the headers look like. ex. What does a Pld End of File buffer look like?
- Might end up with some repeated code. 
- Gotta be something I'm missing.....

@ksmith0 : Can you take a look at the above and let me know your thoughts?

**Comment by ksmith0** [comment]
I like the idea of stuffing everything into the DataFile. I would guess that the pld is just a derived ldf DataFile with a couple overridden methods. evt2root tried to compartmentalize every type of buffer you could ever have and then build files from that, but it was a pain to try and squeze certain formats into a given scheme. Many of the above FileBuffer classes would be trivial and could probably just live as methods inside a DataFile class. (I think the name FileBuffer is misleading.)

**Comment by spaulaus** [comment]
> (I think the name FileBuffer is misleading.)

I agree. I just couldn't come up with a better one at the time. 

As I wrote this I too decided that stuffing DataFile to the gills was a good way to go. I'm glad to see I can learn from evt2root. It does sound like breaking out things into individual buffers can be more of a pain than a help. **Alternative plan is a go.**

**Comment by spaulaus** [comment]
@ksmith0  : Are we happy with the name `DataFile` for the abstract class?

**Comment by spaulaus** [comment]
Children would be called `LdfFile`, `PldFile`, and `KissFile`.

**Comment by ksmith0** [comment]
I'm happy with those.

**Comment by spaulaus** [comment]
@ksmith0 : I demand that when you agree with me you always link this picture; 
![image](https://user-images.githubusercontent.com/1553042/29292008-8c5f56fe-8113-11e7-9970-9e7089650705.png)

**Comment by spaulaus** [comment]
I've now laid the groundwork for this to happen. I have created DataFile, PldFile, and LdfFile classes. I've taken the information out of hribf_buffers.h/cpp and put them into the new classes. I need to make a list or map of all the methods to see where there's overlap. 

One point of overlap are all the Read/Write/Close methods. I'm think that it makes sense to have a series of methods to replace the individual ones, i.e. ReadHeader, ReadPhysicsData, ReadEndOfFile, etc. Trying to glom all these into a single Read/Write method might get exceedingly messy to read.

**Comment by spaulaus** [comment]
Here's a list of all the private variables that we have in the three headers. There's enough overlap to abstract out Get/Set methods public. I'll have to think deep thoughts about how to do that since the array lengths are different between the LDF and PLD classes. Maybe we can move to the C++11 supported array container?

| PLD                         | LDF                                    | DataFile                      |
|-----------------------------|----------------------------------------|-------------------------------|
| unsigned int run_num        | unsigned int total_buff_size           | unsigned int max_spill_size   |
| unsigned int max_spill_size | unsigned int run_num                   | unsigned int current_file_num |
| float run_time              | unsigned int unknown[3]                | unsigned int output_format    |
| char format[17]             | char facility[9]                       | unsigned int number_spills    |
| char facility[17]           | char format[9]                         | unsigned int run_num          |
| char start_date[25]         | char type[17]                          | bool debug_mode               |
| char end_date[25]           | char date[17]                          | unsigned int current_depth    |
| char *run_title             | char run_title[81]                     |                               |
| time_t runStartTime         | unsigned int run_num                   |                               |
| time_t runStopTime          | int retval                             |                               |
|                             | unsigned int buffer1[ACTUAL_BUFF_SIZE] |                               |
|                             | unsigned int buffer2[ACTUAL_BUFF_SIZE] |                               |
|                             | unsigned int *curr_buffer              |                               |
|                             | unsigned int *next_buffer              |                               |
|                             | unsigned int bcount                    |                               |
|                             | unsigned int buff_head                 |                               |
|                             | unsigned int buff_size                 |                               |
|                             | unsigned int good_chunks               |                               |
|                             | unsigned int missing_chunks            |                               |
|                             | unsigned int buff_pos                  |                               |

**Comment by spaulaus** [comment]
At the very least I can abstract out

- run_num
- run_time
- runStart/StopTime

**Comment by spaulaus** [comment]
I thinking about how to make the code more [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)). To accomplish that I need to break these out the classes further. We would probably need 

- DataFile - handles the general file definitions and structure
- DataReader - handles reading the file from the disk and parsing a buffer
- DataWriter - handles encoding a buffer and writing the file to data stream

As of right now all of these functions are contained inside of the DataFile class.

**Comment by spaulaus** [comment]
@daerogami has confirmed my thoughts on potentially breaking this out. the DataFile class will handle all of the formatting of the data. Reader/Writer will read and write the data from disk.

**Comment by ksmith0** [comment]
> Maybe we can move to the C++11 supported array container?

Agreed

**Comment by spaulaus** [comment]
With a little research, it's generally preferred that one use a vector
https://stackoverflow.com/questions/441203/proper-way-to-store-binary-data-with-c-stl 

Though after additional reading, std::array will be just as good.

**Comment by spaulaus** [comment]
I have decided to focus my efforts on the PLD file format. It will prevent me from getting into a brain melt overload trying to disentangle all of the different threads.

**Comment by spaulaus** [comment]
I have created the following classes : 

- DataFile
- DataReader
- DataWriter
- PldFile
- PldReader
- PldWriter
- DataBroadcaster

PldFile/Reader/Writer are derived classes from their respective Data counterparts. DataBroadcaster will handle broadcasting the data over some sort of SHM connection.

**Comment by spaulaus** [comment]
I'm working to define the PLD File header. I have the following information: 

- HEAD
- Size of HEADER
- Data Format
- Run Number
- Max Spill Size
- Facility
- Start Date/Time
- End Date/Time
- Title Length
- Title

**Comment by spaulaus** [comment]
We could consider using the ISO Standard for MetaData : https://en.wikipedia.org/wiki/ISO/IEC_11179

**Comment by spaulaus** [comment]
We could also consider ISO Standard for dates : https://en.wikipedia.org/wiki/ISO_8601

**Comment by spaulaus** [comment]
I have decided to include the size of the header as the second word in the header. This will ensure that we always know how big it should be. The size will exclude the HEAD and itself.

**Comment by spaulaus** [comment]
We're not really using the header information for anything other than printing to terminal at this point. I spoke with @ksmith0. We concur that a good use of the head will be to just record all the information via ASCII. We can move more information about the run into other buffers. Here's a brief summary

- HEAD -> Contains simple information about the data file that would be useful for users to read just by doing `less` on the file
- DIGI -> Contains information about the digitizers. It's a repackaging of what we output to the terminal when `poll2` starts up and boots the modules
- SET -> A pure dump of the default.set into the data file. 
- INFO -> A few pieces of information that're needed when reading information back from the file. 

## Header format
- HEAD word
- length of head
- Run Number
- Facility
- Type of Data file
- Start Date/Time
- Stop Date/Time
- Run Title
- EOB

##  DIGI Format
- DIGI word
- DIGI length
- Firmware list from pixie.cfg (or other configuration file)
(repeat these words for each module)
- Slot Number
- Module SN
- Module Frequency
- EOB

## SET Format
- SET word
- SET word length
- Here we just dump the entire contents of the default.set 
- EOB word

## INFO Format
- INFO word
- INFO length
- run time in seconds
- maximum spill size
- EOB
