### ISSUE TITLE
Update XiaData so that it cannot accept slot numbers less than 2

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#16]
The minimum slot a pixie module can have is 2. Therefore, we should have error checking in place to ensure that this is never less than 2.

**Comment by ksmith0** [comment]
This is not completely true. There is the capability in the XIA to change the slotIDs. I believe some others do this. Currently poll2 enforces this, but it doesn't have to.

**Comment by spaulaus** [comment]
Interesting, then would it be safe to say that it can never be less than 0?

**Comment by ksmith0** [comment]
I believe so. Isn't it represented as an unsigned short or something?

**Comment by spaulaus** [comment]
I believe it's an unsigned int. Maybe instead of 0 we initialize it to u_int_max?

**Comment by ksmith0** [comment]
At least one of the firmware versions has slotID as four bits, so it really should be <16.

**Comment by ksmith0** [comment]
You'll save a lot of memory if you have a large number of events. Just be sure there isn't an instance where one firmware has a larger size.

**Comment by spaulaus** [comment]
From the firmwares we have data for, the first half of Header Word 1 is constant.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#16
