### ISSUE TITLE
Correct XIA Firmware Revisions

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#20]
The [wiki](https://github.com/spaulaus/paass-laughing-conqueror/wiki/Pixie-Firmware-Information) information: 

| Version Number | Release Date  | Sampling Frequencies | Bit Resolutions | 
|:---:|:---:|:---:|:---:|
| 17562 | 15 Dec 2010 | 100       | 12 |
| 20466 | 26 Sep 2011 | 250       | 12 |
| 27361 | 11 Jun 2013 | 250       | 12 |
| 29432 | 15 Feb 2014 | 100, 250, 500 | 12, 14 |
| 30474 | 28 Jul 2014 | 100, 250, 500 | 12, 14 |
| 30980 | 01 Oct 2014 | 100, 250, 500 | 12, 14 |
| 30981 | 01 Oct 2014 | 100, 250, 500 | 12, 14 |
| 39432 | 08 Mar 2016 | 100, 250, 500 | 12, 14, 16 |

does not match what is reflected in [HelperEnumerations.cpp](https://github.com/spaulaus/paass-laughing-conqueror/blob/dev/Resources/include/HelperEnumerations.hpp#L28): 
```cpp
    ///An enum for the different firmware revisions for the Pixie-16 modules.
    /// * R17562 is valid from 12/15/2010 to 09/26/2011 (this is primarily a
    /// Rev D firmware, i.e. 100 MS/s)
    /// * R20466 is valid from 09/26/2011 to 06/11/2013
    /// * R27361 is valid from 06/11/2013 to 02/15/2014
    /// * R29432 is valid from 02/15/2014 to 07/28/2014
    /// * R30474, R30980, R30981 is valid from 07/28/2014 to 03/08/2016
    /// * R29432 is valid from 03/08/2016
    /// * UNKNOWN is used for unspecified firmware revisions.
    ///These dates do not imply that the particular data set being analyzed was
    /// taken with the expected firmware. These dates are meant only to help
    /// guide the user if they do not know the particular firmware that was used
    /// to obtain their data set.
    enum FIRMWARE {
        R17562, R20466, R27361, R29432, R30474, R30980, R30981, R34688, UNKNOWN
};
```

or in [XiaListModeDataMask.cpp](https://github.com/spaulaus/paass-laughing-conqueror/blob/dev/Analysis/ScanLibraries/source/XiaListModeDataMask.cpp#L41):
```cpp
    if (firmwareNumber >= 17562 && firmwareNumber < 20466)
        firmware = R17562;
    else if (firmwareNumber >= 20466 && firmwareNumber < 27361)
        firmware = R20466;
    else if (firmwareNumber >= 27361 && firmwareNumber < 29432)
        firmware = R27361;
    else if (firmwareNumber >= 29432 && firmwareNumber < 30474)
        firmware = R29432;
    else if (firmwareNumber >= 30474 && firmwareNumber < 30980)
        firmware = R30474;
    else if (firmwareNumber >= 30980 && firmwareNumber < 30981)
        firmware = R30980;
    else if (firmwareNumber >= 30981 && firmwareNumber < 34688)
        firmware = R30981;
    else if (firmwareNumber ==
             34688) //compare exactly here since nothing higher
        firmware = R34688;
    else {
        msg << "XiaListModeDataMask::CovnertStringToFirmware : "
            << "Unrecognized firmware option - " << type << endl;
        throw invalid_argument(msg.str());
}
```

**Comment by spaulaus** [comment]
While working on #31, I removed the huge block comment for the firmware and simply provide a link to the wiki. Fewer places of documentation the better since we know the rule about documentation. The list of  firmwares in `XiaListModeDataMask::ConvertStringToFirmware` are consistent w/ the `enum` and with the wiki.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#20
