### ISSUE TITLE
Question about Ncurses

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#21]
Is there ever a situation where we would not require ncurses? I honestly can't think of one. 

If we always require it then we can definitely get rid of the CMake flag along with all the `if(NCURSES_FOUND)` lines.

**Comment by ksmith0** [comment]
The idea behind this was to be backward supportable to the poll1 era. We wanted to extend the terminal functionality through ncurses, but we were supporting a machine on which it was hard to install (standalone I believe). One could envision that the poll2 application could run without ncurses, but at a reduced terminal functionality. In addition, you could run the scan utilities without a terminal to do batch work. There is a basic terminal somewhere, but I bet it hasn't been tested in some time and may not function correctly.

On the other hand, most systems have ncurses in the repos so it is not a heavy prerequisite. It would also reduce the code base and thus make maintenance easier.

**Comment by spaulaus** [comment]
I think that having ncurses as a prerequisite shouldn't be an issue. As you say, it's in the package manager for nearly every modern system.

**Comment by ksmith0** [comment]
I support making ncurses a full prerequisite.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#21
