### ISSUE TITLE
Error compiling Correlator w/ utkscan

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#23]
@jjvz reported having an issue compiling Correlator.
```c++
/opt/paass/Analysis/Utkscan/core/source/Correlator.cpp:200:32: error: call of overloaded ‘isnan(double&)’ is ambiguous
             if (!isnan(lastTime)) {
```

I still think it's weird that these types of issues are caught by some compilers and not caught by others.

**Comment by ksmith0** [comment]
What compiler is this? Have we tried compiling PAASS with gcc 7? I can do this if needed.

**Comment by spaulaus** [comment]
My compiler version : 
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

**Comment by spaulaus** [comment]
You know this is one of the reasons I wish I was still on arch. F-buntu.

**Comment by spaulaus** [comment]
I just realized this is blowing up a new slack channel and my crazy comments are actually broadcast for people to see.....

**Comment by spaulaus** [comment]
> What compiler is this? Have we tried compiling PAASS with gcc 7? I can do this if needed.

JJ reports that they're using gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

Maybe not necessary yet. I'm going to figure out how to get some arch action.

**Comment by spaulaus** [comment]
Issues were seen in `Correlator.cpp` and `ImplantSsdProcessor.cpp` according to TravisCI.

**Comment by spaulaus** [comment]
Unfortunately, I couldn't replicate these on my local machine, so I'll have to use the CI server as a test.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#23
