### ISSUE TITLE
poll2 --prefix

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#26]
# Business Value
This no longer works as expected. I expect it was lost when pacman mode was added as both flags start with the letter p.

# Functional Requirements
1. CMake configures all the necessary paths during the build.

# Developer Notes
1. This functionality is only used in [viewBaseline](https://github.com/spaulaus/paass-laughing-conqueror/search?utf8=%E2%9C%93&q=%22poll2+--prefix%22&type=)

**Comment by ksmith0** [comment]
I think this commit 48228fc51008fda1fa0b9bdb3a546961f0111ebc is the cause.

**Comment by ksmith0** [comment]
This impacts the functionality of viewTraces.

# Workaround
This can be worked around by first making local version of files:
```
cp /opt/paass/bin/viewBaseline /opt/paass/share/traces/tra .
```
 Modify viewBaseline line 15 to read:
```
gnuplot -e "MOD=$mod;CH=$ch" tra
```
and modify tra line 16 to read
```
dir = "/opt/paass/share/traces/"
```

**Comment by ksmith0** [comment]
We don't really need prefix for this do we? We could use CMake to configure these files with hard coded paths from `CMAKE_INSTALL_PREFIX`. I'm not sure why I originally decided to go down the prefix road.

**Comment by ksmith0** [comment]
This functionality is only used in the viewBaseline package:

https://github.com/spaulaus/paass-laughing-conqueror/search?utf8=%E2%9C%93&q=%22poll2+--prefix%22&type=

**Comment by spaulaus** [comment]
The issue presents itself to the user as 
```
[pr270user@asouev2 poll]$ viewBaseline 0 -1
Cannot open load file 'Creating'
"Creating", line 0: util.c: No such file or directory
```

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#26
