### ISSUE TITLE
Get ROOT running on the CI Server

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#28]
We have yet to get root installed, running, and tested on the CI server.

**Comment by ksmith0** [comment]
Reading through the ROOT forum I found this:
> mato Jun 16
> Why do not install the ubuntu 14 binaries?
> https://root.cern.ch/download/root_v6.10.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz5

___Source: https://root-forum.cern.ch/t/root-library-problems-on-ubuntu-14-04-with-gcc-5-4-1/25139/7?u=ksmith___

Have we tried to install the ROOT binaries?

**Comment by spaulaus** [comment]
I tried that but it complained about the compiler version.

**Comment by ksmith0** [comment]
Could we switch to gcc 4 to get the ROOT running? Maybe we do a separate build for gcc 4 and 5?

**Comment by spaulaus** [comment]
This is something I haven't put in a ticket for. I'd like to get the matrix setup properly to test with various versions of gcc

**Comment by spaulaus** [comment]
https://root-forum.cern.ch/t/continuous-integration/26252/9
