### ISSUE TITLE
Update FindXIA.cmake to handle new directory structure

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#38]
I've been thinking about a new structure for the xia folder. I think it will make it easier to organize the files. 
# Current structure
- **/opt**
  - **xia**
    - **current** (symlink to desired firmware folder)
    - **2016-02-02-12b250m-vandle** (or another specific firmware folder)
      - **configuration** (set files for DSP and slot_def.set)
      - **dsp** (the files that tell the DSP how to process and package data, provides the firmware and frequency numbers for analysis.)
      - **firmware** (the files that get loaded up onto the FPGAs)
      - **software** (this contains the API libraries)
      - **test** (some test software provided by XIA)

## Limitations of directory structure
This structure is rather inefficient. The software and test directories do not change as frequently as the firmware. The last update to these directories was March 21, 2016. But we've had additional firmware revisions since then. In fact, we sometimes have new firmware every experiment. 

Sometimes the firmware is provided without the `configuration`, `software`, or `test` directories. One sometimes has to symlink these directories into the firmware folder. I don't particularly like this since it means that we may forget the symlinks exist, or the linked folder may get moved by accident.

# Proposed Structure
- **/opt**
  - **xia**
    - **api**  - files provided by the XIA API
      - **lib** - API libraries
      - **include**  - API includes
    - **share**
      - **pxisys** - contains the pxisys*.ini files provided in the API
      - **slotdef** - probably just a single slot def, can be added to the API install
    - **firmware**
      - **2016-02-02-12b250m-vandle**  (and other specific firmware)
        - **config** - not something that XIA distributes on their website, **DO NOT** add to repos
        - **dsp**
        - **fpga**

## Advantages
The software only has to worry about looking in a single place for the API. We don't need to symlink or make multiple copies of the API. We know which API the software was compiled against. It's simple to add firmware w/o duplicating files. It's clear about where we can find the information we need. 

## Disadvantage
The directory structure is different than that provided by XIA, You have to do a little work to get the firmware into the right place. 

## Bonus
Since the xia-api is now in a cmake project we could automatically install it using the PAASS Cmake as a submodule.

**Comment by spaulaus** [comment]
@ksmith0 : Hit me with your thoughts on this.

**Comment by ksmith0** [comment]
I like it in general, but have a couple issues:

* The fact that this is not the default shipping may become problematic. An install script would be useful. 
* `share/setfiles` Some of these setfiles change when the firmware changes as new options are added. This becomes problematic when they are not tracked with the firmwares.
* I'd move `current` under `firmwares`. Maybe change it to `default`?

**Comment by spaulaus** [comment]
> The fact that this is not the default shipping may become problematic. An install script would be useful.

The install script would be just as problematic since it requires us to keep up with any changes that XIA makes. 

> share/setfiles Some of these setfiles change when the firmware changes as new options are added. This becomes problematic when they are not tracked with the firmwares.

The setfiles are always a set size and the var file provides the appropriate mapping. This is an ongoing problem that is out of our control at some level. 

> I'd move current under firmwares. Maybe change it to default?

I concur with this.

**Comment by ksmith0** [comment]
>The install script would be just as problematic since it requires us to keep up with any changes that XIA makes.

But it does allow us control over where things go. We would throw an error if we find something unexpected and then the user has to deal with it.
> The setfiles are always a set size and the var file provides the appropriate mapping. This is an ongoing problem that is out of our control at some level.

I believe we really only want a default set file here anyway so we might as well package it with the firmware and not worry about a separate directory.

**Comment by spaulaus** [comment]
> But it does allow us control over where things go. We would throw an error if we find something unexpected and then the user has to deal with it.

So does just copy/pasting the updated files into the cmake structure. 



> I believe we really only want a default set file here anyway so we might as well package it with the firmware and not worry about a separate directory.

I don't think XIA distributes a default.set publicly. We're not distributing any firmware here. It's important to make that distinction!

**Comment by ksmith0** [comment]
>So does just copy/pasting the updated files into the cmake structure.

What do you mean by 'cmake structure'?

**Comment by spaulaus** [comment]
I mean that when XIA releases a new version of the API, we can just copy/paste the files from the package into the new directory structure. This is really no different than having an install script. Except that we don't have to worry about fixing a bash script if somebody finds an error on their machine. CMake will handle it all for us. 

 If we can get the test programs compiled with the cmake rewrite, then I'm going to send it to Hui and see if they're willing to support it.

**Comment by ksmith0** [comment]
CMake now searches the /opt/xia/api directory when looking for the xia software. As of commit 83a5461b5068f34e1dc7c763ff69b02dc3a9c788

**Comment by ksmith0** [comment]
Currently the [spaulaus/xia-api](https://github.com/spaulaus/xia-api) does not install the include directories which leads to acquisition build failures.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#38
