### ISSUE TITLE
Warn user if firmware is beyond known valid values.

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#41]
The firmware is constantly being updated and often we can unpack it using the previous algorithms, but this is not guaranteed. I suggest we warn the user that the unpacking may fail and then attempt to use the old algorithm anyway.

**Comment by spaulaus** [comment]
I think that's probably a good idea.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#41
