### ISSUE TITLE
invalid_argument thrown when calling stoi

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#47]
![image](https://user-images.githubusercontent.com/1553042/30983730-40f6169e-a459-11e7-97c0-d3a8e450ba18.png)

Not sure where the error is coming from. But I think the mask is a good place to start.

**Comment by ksmith0** [comment]
A backtrace would tell you where.

**Comment by spaulaus** [comment]
Yep, I know. I just haven't had a chance to run it.

**Comment by spaulaus** [comment]
It's like I have a job or something.

**Comment by spaulaus** [comment]
This isn't an issue, it's just a stupid user. 
![image](https://user-images.githubusercontent.com/1553042/30991370-c908167c-a472-11e7-9989-7ef114470fc2.png)

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#47
