### ISSUE TITLE
Update includes to have new standard

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#50]
# Business Value
We need a new standard for headers that will help prevent some of these compilation issues where things go missing on different compilers. Here's one suggestion:

- dir2/foo2.h (preferred location — see details below).
- Your project's .h files.
- Other libraries' .h files.
- C++ system files.
- C system files.

The advantage here is that we put ourselves first. If we end up missing any dependencies then we catch them pretty quick. This also means that our headers can be cleaner since we'll be taking care of dependencies without having to repeat ROOT, C and C++ headers. 

# Functional Requirements
1. All header and source files in the code adhere to the above inclusion scheme. 

# Developer Notes
1. 

# Resources
1. https://stackoverflow.com/a/614333
1. https://stackoverflow.com/a/14243688

**Comment by spaulaus** [comment]
@ksmith0 : Do you see any issues with this ?

**Comment by ksmith0** [comment]
I’m not sure I completely understand it.

**Comment by spaulaus** [comment]
The goal is to alleviate some of the weird compilation issues when we move between platforms. If we standardize our includes, then we should help uncover most of these hidden dependencies. The key here is that we include all of our internal project files before we add any 3rd party or STL libraries.

**Comment by ksmith0** [comment]
I’m not sure that is possible. If you have `includeA.h` that depended on `vector` and `includeB.h` that depends on `iostream`, how would you organize them such that STL is loaded last? Why do we want STL loaded last, I’m not seeing how this makes anything better.

**Comment by spaulaus** [comment]
Loading STL last only applies locally. What this allows I'd for us to ensure we don't have hidden dependencies that may rear their head when we compile on a new machine. 

https://stackoverflow.com/a/614333
https://stackoverflow.com/a/14243688

**Comment by ksmith0** [comment]
Thanks for the examples, it is clear now. I support this now that I understand it.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#50
