### ISSUE TITLE
Remove HRIBF integration and dependence

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#6]
# Business Value
I'm putting this here mostly to discuss this topic. I think we should remove the HRIBF dependence (pacman mode, USE_HRIBF, utkscanor, etc. This causes an unnecessary amount of clutter for something that we do not intend to use. 

# Functional Requirements
1.  TBD

**Comment by spaulaus** [comment]
I think it would also serve as an impetus to actually shore up our online deficiencies.

**Comment by ksmith0** [comment]
I like the idea of getting away from these dependencies, but substantial work would need to be done to shore up the "new" online utilities. In addition we would need to perform testing to make sure it is reliable. I propose we open a project for this and outline the way forward.

**Comment by spaulaus** [comment]
I was thinking that we can remove is in stages. Removal from Analysis first then removal from Acquisition. I don't see that this code is going to be used in a "real" experiment any time soon.

**Comment by spaulaus** [comment]
I actually think we ought to keep utkscanor at this point. We should just tighten up the logic and rely less on preprocessors defines

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#6
