### ISSUE TITLE
Add a help menu to RootScanner

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#79]
# Description
There is no way to understand the commands supported by RootScanner without reading the source code.

# Acceptance Criteria
1. The user is provided a list of commands when typing `help`

**Comment by spaulaus** [comment]
@ksmith0 , I do not believe that this is an issue. Rootscan provides the following when typing the `help` command: 
![image](https://user-images.githubusercontent.com/1553042/35415993-7f83ae72-01f5-11e8-8132-c66a438210eb.png)

This provides users with the requested information. @jjvz can you confirm that this meets your requirements?

**Comment by ksmith0** [comment]
Sorry I misunderstood @jjvz screen shot of the help choices. It was from the command line not from within rootscan.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#79
