### ISSUE TITLE
CMake auto clone submodules.

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-laughing-conqueror#8]
Users with less knowledge of git may get tripped up by the fact that the submodules are not initialized and updated. We can use the following code segment to handle that automatically for them.

```cmake
#Check if the submodule has been cloned. If not we do it for the user.
set(SUBMODULE_NAME "submodule")
file(GLOB SUBMODULE_FILES "${CMAKE_SOURCE_DIR}/${SUBMODULE_NAME}/*" )
list(LENGTH SUBMODULE_FILES NUM_SUBMODULE_FILES)
if (${NUM_SUBMODULE_FILES} EQUAL 0)
   message(STATUS "Cloning '${SUBMODULE_NAME}' submodule.")
   execute_process(COMMAND git submodule update --init ${CMAKE_SOURCE_DIR}/${SUBMODULE_NAME})
endif (${NUM_SUBMODULE_FILES} EQUAL 0)
```
The above code segment could be stuck in a loop over all submodules.

An alternate approach is to check for the `.git` file, but this may cause issues for instances that are downloaded as a zip as they do not contain the git files.

**Comment by spaulaus** [comment]
I think I like the ExternalProject mentioned in #7 better.

**Comment by spaulaus** [comment]
At the moment we do not have any submodules defined by the software. I'm going to close this out and we'll use the ExternalProject features of CMake.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#8
