### ISSUE TITLE
Building unittests fails if we can't find ROOT

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-laughing-conqueror#82]
# Business Value
If we use this build commend on a system **without** ROOT installed. The build fails. 
```bash
cmake ../ -DPAASS_BUILD_UTKSCAN=TRUE -DPAASS_BUILD_TESTS=TRUE
```
# Acceptance Criteria
1. The build succeeds with this scenario.

**Comment by spaulaus** [comment]
The scripts don't always fail, strangely enough. It looks like the newest images are using gcc7. I think it's time to get us up-to-date.

**Comment by spaulaus** [comment]
@ksmith0 : Can you try to reproduce this bug? I cannot.

**Comment by spaulaus** [comment]
I can't get this to happen again.

**Comment by spaulaus** [comment]
I figured this one out. The issue is `USE_ROOT` defaults to `ON`. ROOT is defined as `REQUIRED` in the `find_package` function, which causes the failure. Therefore, systems without ROOT are not able to build unless `USE_ROOT=OFF`

**Comment by spaulaus** [comment]
I'm brainstorming a way that this can be a little less opaque for users.

**Comment by spaulaus** [comment]
@ksmith0 : What if we remove the `USE_ROOT` flag, and make ROOT an optional dependency instead of required? That way ROOT related stuff is built if it's found and not built if it's not. We can use the `ROOT_FOUND` variable to replace `USE_ROOT` in all the if statements.

**Comment by ksmith0** [comment]
The drawback to this is that the end user misses out on the ROOT capabilities without knowing it. This is of course if they decide to just jump in the deep end without looking at the README or wiki. I'm in support of changing this to optional.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#82
